### ISSUE TITLE
private_networkが設定されない

### ISSUE THREAD

**Issue by ghost** [ytake/gardening#5]
以下のような`vagrant.yml`で`vagrant up`するとprivate_networkが設定されませんでした。

```
ip: "192.168.10.14"
memory: 4096
cpus: 1
hostname: myapp
name: myapp
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    - map: ./
      to: /home/vagrant/myapp
sites:
    - map: myapp.app
      to: "/home/vagrant/myapp/public"
      hhvm: false
elasticsearch: false
fluentd: true
mongodb: false
couchbase: true
```

```
[vagrant@myapp:~/myapp]$ ifconfig
enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fef6:b007  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:f6:b0:07  txqueuelen 1000  (Ethernet)
        RX packets 712  bytes 79932 (78.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 468  bytes 67736 (66.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 622  bytes 67842 (66.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 622  bytes 67842 (66.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

`scripts/builder.rb`のネットワーク設定に`auto_config:false`を指定すると設定されました。

```
    # Configure A Private Network IP
    config.vm.network :private_network, ip: settings["ip"] ||= "192.168.10.10", auto_config:false
```

```
[vagrant@myapp:~/myapp]$ ifconfig
enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fef6:b007  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:f6:b0:07  txqueuelen 1000  (Ethernet)
        RX packets 352  bytes 40338 (39.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 241  bytes 34846 (34.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::a00:27ff:fe56:d9af  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:56:d9:af  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 888 (888.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 366  bytes 41455 (40.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 366  bytes 41455 (40.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

HOST: macOS Sierra 10.12.2
GUEST: CentOS Linux release 7.1.1503 (Core)
Vagrant: 1.9.1
